# Generated by Django 5.0.4 on 2024-04-30 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, db_column='date_of_birth', null=True, verbose_name='Date of Birth')),
                ('address', models.CharField(blank=True, db_column='address', max_length=255, null=True, verbose_name='Address')),
                ('city_town', models.CharField(blank=True, db_column='city_town', max_length=150, null=True, verbose_name='City/Town')),
                ('country', models.CharField(blank=True, db_column='country', max_length=150, null=True, verbose_name='Country')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Profile Picture')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'Student',
                'ordering': ['-id'],
            },
        ),
    ]
